language: c
matrix:
  include:
    - os: osx
      env: TARGET_MACHINE=a6osx
    - os: linux
      env: TARGET_MACHINE=i3le
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - lib32ncurses5-dev
            - libx32ncurses5-dev
            - uuid-dev:i386
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - os: linux
      env: TARGET_MACHINE=a6le
      before_script:
        - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
    - os: windows
      env: TARGET_MACHINE=a6nt
      before_script:
        - git config core.autocrlf false
        - rm .git/index
        - git reset --hard
        - choco install make -y
        - choco install python2 -y
    - os: windows
      env: TARGET_MACHINE=i3nt
      before_script:
        - git config core.autocrlf false
        - rm .git/index
        - git reset --hard
        - choco install make -y
        - choco install python2 -y
dist: xenial
script:
  - .travis/get-chez-scheme.sh
  - .travis/build.sh
  - .travis/test.sh
